CREATE TABLE `geometry_columns` (
	`F_TABLE_CATALOG` VARCHAR(256) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`F_TABLE_SCHEMA` VARCHAR(256) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`F_TABLE_NAME` VARCHAR(256) NOT NULL COLLATE 'utf8mb4_general_ci',
	`F_GEOMETRY_COLUMN` VARCHAR(256) NOT NULL COLLATE 'utf8mb4_general_ci',
	`COORD_DIMENSION` INT(11) NULL DEFAULT NULL,
	`SRID` INT(11) NULL DEFAULT NULL,
	`TYPE` VARCHAR(256) NOT NULL COLLATE 'utf8mb4_general_ci'
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
