CREATE TABLE `demanda` (
	`OGR_FID` INT(11) NOT NULL AUTO_INCREMENT,
	`SHAPE` GEOMETRY NOT NULL,
	`demanda` VARCHAR(80) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`distancia` DOUBLE(21,6) NULL DEFAULT NULL,
	UNIQUE INDEX `OGR_FID` (`OGR_FID`) USING BTREE,
	INDEX `SHAPE` (`SHAPE`(32))
)
COLLATE='utf8mb4_general_ci'
ENGINE=MyISAM
AUTO_INCREMENT=122
;
